// Only the ones we actually used
export const toMigrateStandardizedNames = {
  'Adductor/Groin': 'Seated Machine Hip Adductor',
  'Air Bike': 'Air Bike',
  'Back Extensions': 'Lying Back Extension',
  'Barbell Bench Press - Medium Grip': 'Barbell Wide Bench Press',
  'Barbell Curl': 'Barbell Biceps Curl',
  'Barbell Deadlift': 'Barbell Deadlift',
  'Barbell Incline Bench Press - Medium Grip': 'Barbell Incline Bench Press',
  'Barbell Shrug': 'Barbell Shrugs',
  'Barbell Squat': 'Barbell Full Squat',
  'Bent Over Barbell Row': 'Barbell Bent Over Row',
  'Bicycling, Stationary': 'Stationary Bike',
  'Bulgarian Split Squat ': 'Bulgarian Split Squat',
  'Cable Overhead Triceps Extension': 'Cable Overhead Extension Rope',
  'Chin-Up': 'Chin Up',
  'Deficit Deadlift': 'Barbell Deadlift',
  'Dips - Chest Version': 'Chest Dip Weighted',
  'Dips - Triceps Version': 'Chest Dip Weighted',
  'Dumbbell One-Arm Shoulder Press': 'Dumbbell Single Arm Shoulder Press',
  'Dumbbell Shoulder Press': 'Dumbbell Standing Shoulder Press',
  'EZ-Bar Curl': 'Ez Bar Biceps Curl Normal Grip',
  'Elliptical Trainer': 'Elliptical Trainer',
  'Forearm machine': null,
  'Front Barbell Squat': 'Barbell Front Squats',
  'Front Dumbbell Raise': 'Dumbbell Standing Front Raise',
  Hang: 'Dead Hang Stretch',
  'Hanging Leg Raise': 'Hanging Knee Raises',
  'Hyperextensions (Back Extensions)': 'Lying Back Extension',
  'Incline Dumbbell Benchpress ': 'Incline Bench Dumbbell Chest Press',
  'Incline Dumbbell Curl': 'Dumbbell Incline Alternate D Curl',
  'Lat Pulldown': 'Cable Pulldown',
  'Leg Extensions': 'Leg Extension',
  'Leg Press': 'Leg Press Machine Normal Stance',
  'Lying Hamstring Curl': 'Leg Curl Machine Lying',
  'Lying Leg Curls': 'Leg Curl Machine Lying',
  'Lying T-Bar Row': 'Landmine Row',
  'Machine Flyes': 'Machine Fly',
  'Machine flyes': 'Machine Fly',
  'Machine shoulder raise': 'Machine Lateral Raise',
  'One Leg Barbell Squat': 'Barbell Single Leg Split Squat',
  'One-Arm Dumbbell Row': 'Dumbbells Bent Over Row',
  'One-Arm Incline Lateral Raise': 'Dumbbell Incline Lateral Raises',
  'Overhand ez bar curl': 'Barbell Reverse Biceps Curl',
  'Preacher Curl': 'Barbell Preacher Curl',
  'Pull up': 'Pull Up Normal Grip',
  'Pull up neutral grip': 'Chin Ups Narrow Parallel Grip',
  'Pull-Up': 'Pull Up Normal Grip',
  'Reverse Barbell Curl': 'Barbell Reverse Biceps Curl',
  'Reverse Grip Bent-Over Rows': 'Barbell Bent Over Rows Reverse Grip',
  'Ring Face Pull': null,
  'Rings Triceps Push': null,
  'Rope Pushdown': 'Cable Pushdown',
  'Seated Cable Rows': 'Cable Seated Row',
  'Seated Calf Raise': 'Seated Calf Machine',
  'Seated Hamstring Curl': 'Leg Curl Machine Seated',
  'Seated One-arm Cable Pulley Rows': 'Cable Seated One Arm Alternate Row',
  'Seated pull machine neutral grip': 'V Bar Seated Cable Row Machine',
  'Side Lateral Raise': 'Dumbbell Lateral Raises',
  'Split Squat': 'Bulgarian Split Squat',
  'Standing Calf Raises': 'Hack Squat Machine Calf Raise',
  'Standing Military Press': 'Barbell Standing Shoulder Press',
  'Step Mill': 'Step Mill',
  'Supinated Lat Pulldown': 'Lat Pull Down Reverse Grip',
  Threadmill: 'Treadmill Run',
}
