export default {
  newWorkout: 'New workout',
  addExercise: 'Add exercise',
  selectExercise: 'Select exercise',
  copyWorkout: 'Copy workout',
  addSet: 'Add set',
  search: 'Search',
  reps: 'reps',
  weight: 'weight',
  distance: 'distance',
  time: 'time',
  updateSet: 'Update set',
  remove: 'Remove',
  calendar: 'Calendar',
  goToWorkout: 'Go to workout',
}
