export default {
  primary: '#764abc',
  secondary: '#f4f4f4',
  critical: 'red',
  tertiary: 'transparent',
  iconBG: '#dfdfdf',
  primaryText: 'white',
  secondaryText: 'black',
  iconText: 'white',
  criticalText: 'white',
  tertiaryText: 'black',
  red: '#d91a1a',
  green: '#15a015',
  yellow: '#FFBF00',
  gray: '#626262',
  lightgray: '#F7F3F9',
  white: '#ffffff',
}
