export default {
  primary: '#764abc',
  secondary: '#f4f4f4',
  critical: '#B22222',
  tertiary: 'transparent',
  iconBG: '#dfdfdf',
  primaryText: 'white',
  secondaryText: 'black',
  iconText: 'white',
  criticalText: 'white',
  tertiaryText: 'black',
  lightred: '#FFCDD2',
  red: '#F44336',
  lightgreen: '#C8E6C9',
  green: '#4CAF50',
  lightyellow: '#FFF176',
  yellow: '#FFEB3B',
  gray: '#626262',
  disabled: '#C0C0C0',
  lightgray: '#F7F3F9',
  white: '#ffffff',
}
