export default {
  primary: '#764abc',
  primaryLight: '#AB9FCF',
  primaryLighter: '#E7E0EC',
  secondary: '#FF6347',
  secondaryLight: '#FF9987',
  secondaryLighter: '#FFD4C4',
  neutralDark: '#626262',
  neutral: '#F7F3F9',
  critical: '#B22222',
  tertiary: 'transparent',
  primaryText: 'white',
  secondaryText: 'white',
  neutralText: 'black',
  iconText: 'white',
  criticalText: 'white',
  tertiaryText: 'black',
  tealDark: '#008080',
  red: '#F44336',
  green: '#4CAF50',
  yellow: '#FFEB3B',
  disabled: '#C0C0C0',
  white: '#ffffff',
}
