export default {
  primary: '#764abc',
  primaryLight: '#AB9FCF',
  primaryLighter: '#E7E0EC',
  secondary: '#f4f4f4',
  critical: '#B22222',
  tertiary: 'transparent',
  primaryText: 'white',
  secondaryText: 'black',
  iconText: 'white',
  criticalText: 'white',
  tertiaryText: 'black',
  tealDark: '#008080',
  red: '#F44336',
  green: '#4CAF50',
  yellow: '#FFEB3B',
  gray: '#626262',
  disabled: '#C0C0C0',
  lightgray: '#F7F3F9',
  white: '#ffffff',
}
